; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.13 on Tue Oct 04 2022 13:49:14 GMT-0500 (Central Daylight Time)
; Wait for set temperatures to be reached
M116 P0

